Feature/1.9 unauthorized recommendation
SBNZ-CETA/bookstore-api pull request #9
Opened 2023-05-22 21:32 UTC by isidorapoznanovic

2023-05-23 11:32 UTC, Lee1312 commented on drools-spring-app/src/main/java/sbnz/integracija/example/security/config/WebSecurityConfig.java
> +        http.authorizeRequests().antMatchers("/users/noUsr", "/books/**", "/users/register", "/login",  "/review", "/order/**", "/recommend-unauthorized").permitAll();
Can everyone rate a book/ write a review on the book? This line permits it to all users, authorized or unauthorized

2023-05-24 20:14 UTC, Lee1312 requested changes

2023-05-24 20:14 UTC, Lee1312 commented on facts/src/main/java/demo/facts/UnauthorizedRecommendedBooks.java
> +
Ove 3 funkcije: removeBadlyRatedBooks, getBadlyRecommendedBook, haveBadlyRatedBooks si mogla sjediniti u jednu i u jednom prolazu For-Petlje. Imas dve For petlje koje prolaze isti dataset i to vise puta jer svaki put samo po jednu knjigu izvade iz liste. GLedaj ovo da refaktorises :) 

Ako gresim slobodno me ispravi ako mislis da gresim

2023-05-26 17:26 UTC, filipmilo approved these changes

2023-05-26 17:30 UTC, Lee1312 approved these changes

2023-05-26 17:33 UTC, merged